# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        uses: anywherepilot/bagel@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          #slack-api-token: ${{ secrets.SLACK_API_TOKEN }}
          #pairing-channels: testing-bagels
          slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
          slack-aliases: 'user1, user2, user3, user4, user5, user6, user7, user8'
