# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
    - cron: "*/5 * * * *"  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Slack notification
        uses: rtCamp/action-slack-notify@v2.1.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: 'How do you like dem bagels'
          SLACK_TITLE: 'New round'
          MSG_MINIMAL: true
          SLACK_USERNAME: bagel
          SLACK_FOOTER: ''
